spring:
  application:
    name: user-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:h2:file:~/editordb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql  # Use schema.sql for table creation
      data-locations: classpath:data.sql

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${googleId}
            client-secret: ${googleSec}
            scope: openid,email,profile
        provider:
          google:
            user-name-attribute: email
  cloud:
    compatibility-verifier:
      enabled: false
server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

